(ns kotoba.shaders
  "Facade re-exporting `kami.shaders` (SSoT). ADR-2607102200 addendum 5."
  (:require [kami.shaders :as k]))

(def lit-fs-body k/lit-fs-body)
(def lit-fs k/lit-fs)
(def G-fields k/G-fields)
(def shadow-fn-body k/shadow-fn-body)
(def VO-fields k/VO-fields)
(def vs-body k/vs-body)
(def shadow-vs-body k/shadow-vs-body)
(def shadow-shader k/shadow-shader)
(def lit-shader k/lit-shader)
(def cascaded-G-fields k/cascaded-G-fields)
(def cascaded-shadow-shader k/cascaded-shadow-shader)
(def cascaded-foliage-shadow-shader k/cascaded-foliage-shadow-shader)
(def cascaded-lit-shader k/cascaded-lit-shader)
(def cascaded-hdr-shader k/cascaded-hdr-shader)
(def cascaded-textured-hdr-shader k/cascaded-textured-hdr-shader)
(def cascaded-textured-lit-shader k/cascaded-textured-lit-shader)
(def bloom-shader k/bloom-shader)
(def atmosphere-cloud-shader k/atmosphere-cloud-shader)
(def hdr-composite-shader k/hdr-composite-shader)
